name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: Build and test
      run: bundle exec fastlane run_unit_tests
